name: QuantAI Training Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'internal_workflow/main_pipeline.py'
      - 'quantai_config.yaml'
      - 'requirements.txt'
      - 'data/raw/XAU_15m_data.csv'
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to configuration file'
        required: true
        default: 'quantai_config.yaml'

jobs:
  train:
    runs-on: ubuntu-latest-xl
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Verify VM Environment
        run: |
          nvidia-smi
          python -c "import tensorflow as tf; print('TensorFlow:', tf.__version__); print('GPU Devices:', tf.config.list_physical_devices('GPU'))"
      
      - name: Install project dependencies
        run: pip install -r requirements.txt
      
      - name: Validate data availability
        run: |
          if [ ! -f "data/raw/XAU_15m_data.csv" ]; then
            echo "ERROR: Data file not found!"
            exit 1
          fi
      
      - name: Execute training pipeline
        env:
          TF_XLA_FLAGS: '--tf_xla_enable_xla_devices --tf_xla_auto_jit=2'
          TF_ENABLE_ONEDNN_OPTS: '1'
        run: python internal_workflow/main_pipeline.py --config ${{ github.event.inputs.config_path || 'quantai_config.yaml' }}
      
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantai-model-output
          path: quantai_output/
          retention-days: 7
