name: QuantAI Training Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'internal_workflow/main_pipeline.py'
      - 'quantai_config.yaml'
      - 'requirements.txt'
      - 'data/raw/XAU_15m_data.csv'
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to configuration file'
        required: true
        default: 'quantai_config.yaml'

jobs:
  train:
    runs-on: ubuntu-latest

steps:
  - name: Checkout kode
    uses: actions/checkout@v4
    
  - name: Optimalkan Lingkungan Komputasi
    run: |
      echo "Memaksimalkan alokasi resource sistem..."
      # Konfigurasi memory limits
      export NODE_OPTIONS="--max-old-space-size=4096"      
      - name: Install project dependencies
        run: pip install -r requirements.txt
      
      - name: Validate data availability
        run: |
          if [ ! -f "data/raw/XAU_15m_data.csv" ]; then
            echo "ERROR: Data file not found!"
            exit 1
          fi
      
      - name: Execute training pipeline
        env:
          TF_XLA_FLAGS: '--tf_xla_enable_xla_devices --tf_xla_auto_jit=2'
          TF_ENABLE_ONEDNN_OPTS: '1'
        run: python internal_workflow/main_pipeline.py --config ${{ github.event.inputs.config_path || 'quantai_config.yaml' }}
      
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quantai-model-output
          path: quantai_output/
          retention-days: 7
